name: Deploy to Toolforge

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Toolforge
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: login.toolforge.org
          username: ${{ secrets.TOOLFORGE_USER }}
          key: ${{ secrets.TOOLFORGE_SSH_KEY }}
          script: |
            become django-oauth-erik << 'BECOME_EOF'
            cd ~/www/python
            git pull origin master
            source venv/bin/activate
            pip install -r requirements.txt
            export TOOLFORGE_DEPLOYMENT=true
            python src/manage.py migrate
            deactivate
            webservice --backend=kubernetes python3.13 restart
            BECOME_EOF
